resourcecontainers
| where type == "microsoft.resources/subscriptions/resourcegroups"
| where subscriptionId == "$subscription"
| where 
    ("$category" == "All") or
    ("$category" == "Prod" and name endswith "-prod") or
    ("$category" == "Client Facing" and (name endswith "-dev" or name endswith "-uat" or name endswith "-qa")) or
    ("$category" == "Nonclient Facing" and not(name endswith "-dev") and not(name endswith "-uat") and not(name endswith "-qa") and not(name endswith "-prod"))
| project name
